---
- name: Configuración de Active Directory en Windows usando PowerShell
  hosts: all
  gather_facts: no
  vars:
    domain_name: "GREENSYS.GRP"
    group_name: "{{ client_name | replace(' ', '') }}GRP"  # Nombre del grupo basado en el nombre del cliente
    gpo_name: "GPO {{ client_name }}"  # Nombre de la GPO clonada
  tasks:
    - name: Verificar conectividad con el servidor de dominio
      win_ping:

    - name: Crear la Unidad Organizativa (OU) usando PowerShell
      win_shell: |
        Import-Module ActiveDirectory
        if (-not (Get-ADOrganizationalUnit -Filter "Name -eq '{{ ou_name }}'" -ErrorAction SilentlyContinue)) {
          New-ADOrganizationalUnit -Name "{{ ou_name }}" -Path "DC=GREENSYS,DC=GRP"
        }
      args:
        executable: powershell

    - name: Crear grupo en la OU usando PowerShell
      win_shell: |
        Import-Module ActiveDirectory
        if (-not (Get-ADGroup -Filter "Name -eq '{{ group_name }}'" -ErrorAction SilentlyContinue)) {
          New-ADGroup -Name "{{ group_name }}" -GroupScope Global -GroupCategory Security -Path "OU={{ ou_name }},DC=GREENSYS,DC=GRP"
        }
      args:
        executable: powershell

    - name: Crear usuarios en la OU usando PowerShell y añadirlos al grupo
      win_shell: |
        Import-Module ActiveDirectory
        $password = ConvertTo-SecureString "{{ default_user_password }}" -AsPlainText -Force
        for ($i = 1; $i -le {{ num_users }}; $i++) {
          # Formato de nombre de inicio de sesión (SamAccountName) con prefijo
          $username = "{{ user_prefix }}{{ client_name }}{0:D2}" -f $i
          $fullname = "{{ client_name }} Puesto {0:D2}" -f $i
          $surname = "Puesto " + "{0:D2}" -f $i
          
          # Verificación y creación del usuario
          if (-not (Get-ADUser -Filter "SamAccountName -eq '$username'" -ErrorAction SilentlyContinue)) {
            New-ADUser -Name $fullname `
                       -GivenName "{{ client_name }}" `
                       -Surname $surname `
                       -SamAccountName $username `
                       -UserPrincipalName "$username@{{ domain_name }}" `
                       -AccountPassword $password `
                       -Path "OU={{ ou_name }},DC=GREENSYS,DC=GRP" `
                       -Enabled $true `
                       -PasswordNeverExpires $true
            
            # Añadir el usuario al grupo
            Add-ADGroupMember -Identity "{{ group_name }}" -Members $username
          }
        }
      args:
        executable: powershell

    - name: Crear y asignar una copia de la Default Domain Policy a la OU
      win_shell: |
        Import-Module GroupPolicy
        $backupPath = 'C:\\tmp'  # Ruta temporal para la copia de seguridad
        New-Item -ItemType Directory -Force -Path $backupPath
        
        
        # Hacer respaldo de la Default Domain Policy y verificar que el respaldo existe
         Backup-Gpo -Name "Default Domain Policy" -Path $backupPath -ErrorAction Stop
        

        # Importar la configuración de la Default Domain Policy a la nueva GPO usando el BackupId
        Import-Gpo -BackupId $backup.BackupId -TargetName "{{ gpo_name }}" -ErrorAction Stop
        
        # Enlazar la nueva GPO a la OU especificada
        $ouPath = "OU={{ ou_name }},DC=GREENSYS,DC=GRP"
        New-GPLink -Name "{{ gpo_name }}" -Target $ouPath -LinkEnabled Yes

        # Limpieza de archivos temporales
        #Remove-Item -Recurse -Force $backupPath
      args:
        executable: powershell
