---
- name: Configuración de Active Directory en Windows usando PowerShell
  hosts: all
  gather_facts: no
  vars:
    domain_name: "GREENSYS.GRP"
    group_name: "{{ client_name | replace(' ', '') }}GRP"  # Nombre del grupo basado en el nombre del cliente
    default_user_password: "ContraseñaDeUsuario"  # Contraseña predeterminada para los nuevos usuarios

  tasks:
    - name: Verificar conectividad con el servidor de dominio
      win_ping:

    - name: Crear la Unidad Organizativa (OU) usando PowerShell
      win_shell: |
        Import-Module ActiveDirectory
        if (-not (Get-ADOrganizationalUnit -Filter "Name -eq '{{ ou_name }}'" -ErrorAction SilentlyContinue)) {
          New-ADOrganizationalUnit -Name "{{ ou_name }}" -Path "DC=GREENSYS,DC=GRP"
        }
      args:
        executable: powershell

    - name: Crear grupo en la OU usando PowerShell
      win_shell: |
        Import-Module ActiveDirectory
        if (-not (Get-ADGroup -Filter "Name -eq '{{ group_name }}'" -ErrorAction SilentlyContinue)) {
          New-ADGroup -Name "{{ group_name }}" -GroupScope Global -GroupCategory Security -Path "OU={{ ou_name }},DC=GREENSYS,DC=GRP"
        }
      args:
        executable: powershell

    - name: Crear usuarios en la OU usando PowerShell con prefijo en el nombre de usuario
      win_shell: |
        Import-Module ActiveDirectory
        $password = ConvertTo-SecureString "{{ default_user_password }}" -AsPlainText -Force
        for ($i = 1; $i -le {{ num_users }}; $i++) {
          # Formato de nombre de inicio de sesión (SamAccountName) con prefijo
          $username = "{{ user_prefix }}{{ client_name }}{0:D2}" -f $i
          $fullname = "{{ client_name }} Puesto {0:D2}" -f $i
          $surname = "Puesto " + "{0:D2}" -f $i
          
          # Verificación y creación del usuario
          if (-not (Get-ADUser -Filter "SamAccountName -eq '$username'" -ErrorAction SilentlyContinue)) {
            New-ADUser -Name $fullname `
                       -GivenName "{{ client_name }}" `
                       -Surname $surname `
                       -SamAccountName $username `
                       -UserPrincipalName "$username@{{ domain_name }}" `
                       -AccountPassword $password `
                       -Path "OU={{ ou_name }},DC=GREENSYS,DC=GRP" `
                       -Enabled $true `
                       -PasswordNeverExpires $true
          }
        }
      args:
        executable: powershell

    - name: Añadir usuarios al grupo usando PowerShell
      win_shell: |
        Import-Module ActiveDirectory
        for ($i = 1; $i -le {{ num_users }}; $i++) {
          $username = "{{ user_prefix }}{{ client_name }}{0:D2}" -f $i
          Add-ADGroupMember -Identity "{{ group_name }}" -Members $username
        }
      args:
        executable: powershell
