---
- name: Configuración de Active Directory en Windows usando microsoft.ad
  hosts: all
  gather_facts: no
  vars_prompt:
    - name: "client_name"
      prompt: "Introduce el nombre del cliente"
      private: no
    - name: "ou_name"
      prompt: "Introduce el nombre de la Unidad Organizativa (OU)"
      private: no
    - name: "num_users"
      prompt: "Introduce el número de usuarios a crear"
      private: no
  vars:
    domain_name: "GREENSYS.GRP"
    group_name: "{{ client_name | replace(' ', '') }}GRP"  # Nombre del grupo basado en el nombre del cliente
    default_user_password: "Y3lm020."  # Contraseña predeterminada para nuevos usuarios

  tasks:
    - name: Verificar conectividad con el servidor de dominio
      win_ping:

    - name: Crear la Unidad Organizativa (OU)
      microsoft.ad.ou:
        name: "{{ ou_name }}"
        path: "DC=GREENSYS,DC=GRP"
        state: present

    - name: Crear grupo en la OU
      microsoft.ad.group:
        name: "{{ group_name }}"
        path: "OU={{ ou_name }},DC=GREENSYS,DC=GRP"
        scope: Global
        type: Security
        state: present

    - name: Crear usuarios en la OU
      microsoft.ad.user:
        name: "{{ client_name }}{{ '%02d' | format(item) }}"  # Formato para usuario con número
        given_name: "{{ client_name }}"
        surname: "Puesto {{ '%02d' | format(item) }}"  # Apellido como "Puesto 01", "Puesto 02", etc.
        path: "OU={{ ou_name }},DC=GREENSYS,DC=GRP"
        password: "{{ default_user_password }}"
        password_never_expires: yes
        state: present
      loop: "{{ range(1, num_users + 1) | list }}"

    - name: Añadir usuarios al grupo
      microsoft.ad.group_membership:
        name: "{{ group_name }}"
        members:
          - "{{ client_name }}{{ '%02d' | format(item) }}"
        state: present
      loop: "{{ range(1, num_users + 1) | list }}"
