---
- name: Configuración de Active Directory en Windows con Tarea Programada para Copiar la GPO
  hosts: windows
  gather_facts: no
  vars:
    domain_name: "GREENSYS.GRP"
    group_name: "{{ client_name | replace(' ', '') }}GRP"  # Nombre del grupo basado en el nombre del cliente
    gpo_name: "GPO {{ client_name }}"  # Nombre de la GPO clonada
    ou_name: "OU_Test"  # Nombre de la OU
  tasks:
    - name: Mostrar un mensaje para confirmar la sesión
      win_shell: |
        Write-Output "Ejecutando como Administrador"
      become: yes
      become_method: runas

    - name: Crear la Unidad Organizativa (OU) en Active Directory
      win_shell: |
        Import-Module ActiveDirectory
        if (-not (Get-ADOrganizationalUnit -Filter "Name -eq '{{ ou_name }}'" -ErrorAction SilentlyContinue)) {
          New-ADOrganizationalUnit -Name "{{ ou_name }}" -Path "DC=GREENSYS,DC=GRP"
        }
      become: yes
      become_method: runas
      args:
        executable: powershell

    - name: Crear grupo en la OU
      win_shell: |
        Import-Module ActiveDirectory
        if (-not (Get-ADGroup -Filter "Name -eq '{{ group_name }}'" -ErrorAction SilentlyContinue)) {
          New-ADGroup -Name "{{ group_name }}" -GroupScope Global -GroupCategory Security -Path "OU={{ ou_name }},DC=GREENSYS,DC=GRP"
        }
      become: yes
      become_method: runas
      args:
        executable: powershell

    - name: Crear usuarios en la OU y añadirlos al grupo
      win_shell: |
        Import-Module ActiveDirectory
        $password = ConvertTo-SecureString "{{ default_user_password }}" -AsPlainText -Force
        for ($i = 1; $i -le {{ num_users }}; $i++) {
          $username = "{{ user_prefix }}{{ client_name }}{0:D2}" -f $i
          $fullname = "{{ client_name }} Puesto {0:D2}" -f $i
          $surname = "Puesto " + "{0:D2}" -f $i
          
          if (-not (Get-ADUser -Filter "SamAccountName -eq '$username'" -ErrorAction SilentlyContinue)) {
            New-ADUser -Name $fullname `
                       -GivenName "{{ client_name }}" `
                       -Surname $surname `
                       -SamAccountName $username `
                       -UserPrincipalName "$username@{{ domain_name }}" `
                       -AccountPassword $password `
                       -Path "OU={{ ou_name }},DC=GREENSYS,DC=GRP" `
                       -Enabled $true `
                       -PasswordNeverExpires $true
            
            Add-ADGroupMember -Identity "{{ group_name }}" -Members $username
          }
        }
      become: yes
      become_method: runas
      args:
        executable: powershell

    - name: Configurar tarea programada para copiar la Default Domain Policy
      win_scheduled_task:
        name: "Copy Default Domain Policy"
        description: "Copia la Default Domain Policy a una nueva GPO y la asigna a la OU especificada"
        actions:
          - path: "powershell.exe"
            arguments: "-NoProfile -ExecutionPolicy Bypass -Command 'Import-Module GroupPolicy; Copy-GPO -SourceName \"Default Domain Policy\" -TargetName \"{{ gpo_name }}\"; $ouPath = \"OU={{ ou_name }},DC=GREENSYS,DC=GRP\"; New-GPLink -Name \"{{ gpo_name }}\" -Target $ouPath -LinkEnabled Yes'"
        trigger:
          - type: once
            start_boundary: "{{ (ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ') + timedelta(seconds=30)).isoformat() }}"
        enabled: yes
      register: scheduled_task

    - name: Esperar 10 segundos para que se complete la tarea programada
      wait_for:
        timeout: 10

    - name: Eliminar la tarea programada después de la ejecución
      win_scheduled_task:
        name: "Copy Default Domain Policy"
        state: absent
