- name: Arrancar el servicio Apache2
  hosts: all
  become: yes  # Necesario para gestionar servicios en Linux
  tasks:
    - name: Arrancar Apache2
      service:
        name: apache2
        state: started
