---
- name: Obtener información del disco en un servidor Linux
  hosts: all
  gather_facts: no
  tasks:
    - name: Ejecutar comando df -h para obtener información del disco
      ansible.builtin.command: df -h
      register: disk_info

    - name: Mostrar información del disco
      debug:
        var: disk_info.stdout
