---
- name: Desplegar Plex en Docker
  hosts: all
  become: true
  tasks:
  
    - name: Descargar la imagen de Plex desde Docker Hub
      community.docker.docker_image:
        name: linuxserver/plex
        source: pull

    - name: Ejecutar contenedor de Plex
      community.docker.docker_container:
        name: plex
        image: linuxserver/plex
        state: started
        restart_policy: always
        ports:
          - "32400:32400"
          - "3005:3005"
          - "8324:8324"
          - "32469:32469"
          - "1900:1900/udp"
          - "32410:32410/udp"
          - "32412:32412/udp"
          - "32413:32413/udp"
          - "32414:32414/udp"
        volumes:
          - /opt/plex/config:/config
          - /opt/plex/data:/data
        environment:
          - PUID=1000
          - PGID=1000
          - VERSION=docker
