---
- name: Consultar la API de Google Cloud Billing
  hosts: localhost
  tasks:
    - name: Obtener datos de facturación de Google Cloud
      uri:
        url: "https://cloudbilling.googleapis.com/v1/billingAccounts/115990250797367456386/billingInfo"
        method: GET
        headers:
          Authorization: "Bearer "
        return_content: yes
      register: billing_info

    - name: Mostrar la información de facturación
      debug:
        var: billing_info.content
