---
- name: Despliegue de aplicación Docker en AWS, Azure y GCP
  hosts: all
  become: yes
  tasks:
    - name: Instalar Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ejecutar aplicación web Docker en AWS, Azure y GCP
      docker_container:
        name: web_app
        image: nginx:latest
        ports:
          - "80:80"
        state: started
