---
- name: Iniciar programa Cosmos en Windows
  hosts: all
  tasks:
    - name: Ejecutar cosrun.exe con los parámetros especificados
      win_shell: >
        F:\COSMOS\Cosmos7.4.2\bin\cosrun.exe -prj F:\CLI\gestiopticas\gestiopticas.prj -arg "-CONNECTION GESTIOPTICAS -USER BORRALOG -OMD borralog -WINDOW FALSE"
      args:
        chdir: F:\COSMOS\Cosmos7.4.2\bin\
      register: resultado
    - name: Mostrar el resultado del comando
      debug:
        var: resultado

