---
- name: Gestionar la cola de impresi贸n en un servidor Windows
  hosts: all
  gather_facts: no
  tasks:
    - name: Parar el servicio de la cola de impresi贸n (Spooler)
      ansible.windows.win_service:
        name: Spooler
        state: stopped

    - name: Verificar el estado del servicio de la cola de impresi贸n
      ansible.windows.win_service_info:
        name: Spooler
      register: spooler_status

    - name: Mostrar el estado del servicio de la cola de impresi贸n
      debug:
        var: spooler_status