---
- name: Descargar todos los archivos .txt desde un FTP usando PowerShell
  hosts: all
  tasks:
    - name: Crear directorio local si no existe
      win_file:
        path: C:\update
        state: directory

    - name: Crear script PowerShell en el servidor con ajuste de filtro de archivos
      win_copy:
        content: |
          $ftpServer = "ftp://10.15.1.26/"
          $username = "update"
          $password = "Y3lm020."
          $localPath = "C:\\update\\"

          Write-Host "Conectando al servidor FTP $ftpServer..."
          
          # Configurar la solicitud FTP
          try {
            $ftpRequest = [System.Net.FtpWebRequest]::Create($ftpServer)
            $ftpRequest.Method = [System.Net.WebRequestMethods+Ftp]::ListDirectory
            $ftpRequest.Credentials = New-Object System.Net.NetworkCredential($username, $password)

            $response = $ftpRequest.GetResponse()
            $responseStream = $response.GetResponseStream()
            $reader = New-Object System.IO.StreamReader($responseStream)
            $fileList = $reader.ReadToEnd()
            $reader.Close()
            $response.Close()

            Write-Host "Lista de archivos obtenida: `n$fileList"

            # Limpiar los nombres de los archivos
            $txtFiles = $fileList -split "`r?`n" | ForEach-Object { $_.Trim() } | Where-Object { $_ -match '\.txt$' }

            if ($txtFiles.Count -eq 0) {
                Write-Host "No se encontraron archivos .txt en el directorio FTP."
            } else {
                Write-Host "Archivos .txt encontrados: $($txtFiles -join ', ')"
            }

            # Descargar cada archivo .txt
            $webclient = New-Object System.Net.WebClient
            $webclient.Credentials = New-Object System.Net.NetworkCredential($username, $password)

            foreach ($file in $txtFiles) {
              $remoteFile = $ftpServer + $file
              $localFile = $localPath + $file
              Write-Host "Descargando archivo $remoteFile a $localFile"
              $webclient.DownloadFile($remoteFile, $localFile)
            }

            Write-Host "Descarga completada."
          } catch {
            Write-Host "Error durante la conexión FTP o la descarga de archivos: $_"
          }
        dest: C:\update\download_ftp.ps1

    - name: Ejecutar el script PowerShell
      win_shell: powershell.exe -ExecutionPolicy Bypass -File C:\update\download_ftp.ps1
