---
- name: Buscar e instalar actualizaciones de Windows
  hosts: all
  gather_facts: no
  tasks:
    - name: Buscar e instalar actualizaciones de Windows
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes  # Esto reinicia automáticamente el servidor si es necesario

    - name: Mostrar las actualizaciones instaladas
      debug:
        var: ansible_facts.packages_installed
